# $Id: rules.mk,v 1.3 1997/10/08 09:54:47 chris Exp $ 
##################################################
#          Do Not Edit This File                 #
#     Add any new modules to files.mk            #
##################################################
argvize.o : $(SRC)/argvize.c
	${CC} -c ${CFLAGS} $(SRC)/argvize.c
atob.o : $(SRC)/atob.c
	${CC} -c ${CFLAGS} $(SRC)/atob.c
bcopy.o : $(SRC)/bcopy.c
	${CC} -c ${CFLAGS} $(SRC)/bcopy.c
cc2str.o : $(SRC)/cc2str.c
	${CC} -c ${CFLAGS} $(SRC)/cc2str.c
errno.o : $(SRC)/errno.c
	${CC} -c ${CFLAGS} $(SRC)/errno.c
exit.o : $(SRC)/exit.c
	${CC} -c ${CFLAGS} $(SRC)/exit.c
getword.o : $(SRC)/getword.c
	${CC} -c ${CFLAGS} $(SRC)/getword.c
index.o : $(SRC)/index.c
	${CC} -c ${CFLAGS} $(SRC)/index.c
lseek.o : $(SRC)/lseek.c
	${CC} -c ${CFLAGS} $(SRC)/lseek.c
malloc.o : $(SRC)/malloc.c
	${CC} -c ${CFLAGS} $(SRC)/malloc.c
printf.o : $(SRC)/printf.c
	${CC} -c ${CFLAGS} $(SRC)/printf.c
queue.o : $(SRC)/queue.c
	${CC} -c ${CFLAGS} $(SRC)/queue.c
rindex.o : $(SRC)/rindex.c
	${CC} -c ${CFLAGS} $(SRC)/rindex.c
sbrk.o : $(SRC)/sbrk.c
	${CC} -c ${CFLAGS} $(SRC)/sbrk.c
sizemem.o : $(SRC)/sizemem.c
	${CC} -c ${CFLAGS} $(SRC)/sizemem.c
stdio.o : $(SRC)/stdio.c
	${CC} -c ${CFLAGS} $(SRC)/stdio.c
str2cc.o : $(SRC)/str2cc.c
	${CC} -c ${CFLAGS} $(SRC)/str2cc.c
str_fmt.o : $(SRC)/str_fmt.c
	${CC} -c ${CFLAGS} $(SRC)/str_fmt.c
strbalp.o : $(SRC)/strbalp.c
	${CC} -c ${CFLAGS} $(SRC)/strbalp.c
strbequ.o : $(SRC)/strbequ.c
	${CC} -c ${CFLAGS} $(SRC)/strbequ.c
strcat.o : $(SRC)/strcat.c
	${CC} -c ${CFLAGS} $(SRC)/strcat.c
strccat.o : $(SRC)/strccat.c
	${CC} -c ${CFLAGS} $(SRC)/strccat.c
strchr.o : $(SRC)/strchr.c
	${CC} -c ${CFLAGS} $(SRC)/strchr.c
strcspn.o : $(SRC)/strcspn.c
	${CC} -c ${CFLAGS} $(SRC)/strcspn.c
strdchr.o : $(SRC)/strdchr.c
	${CC} -c ${CFLAGS} $(SRC)/strdchr.c
strempty.o : $(SRC)/strempty.c
	${CC} -c ${CFLAGS} $(SRC)/strempty.c
strequ.o : $(SRC)/strequ.c
	${CC} -c ${CFLAGS} $(SRC)/strequ.c
strichr.o : $(SRC)/strichr.c
	${CC} -c ${CFLAGS} $(SRC)/strichr.c
striequ.o : $(SRC)/striequ.c
	${CC} -c ${CFLAGS} $(SRC)/striequ.c
stristr.o : $(SRC)/stristr.c
	${CC} -c ${CFLAGS} $(SRC)/stristr.c
strlen.o : $(SRC)/strlen.c
	${CC} -c ${CFLAGS} $(SRC)/strlen.c
strmerge.o : $(SRC)/strmerge.c
	${CC} -c ${CFLAGS} $(SRC)/strmerge.c
strncat.o : $(SRC)/strncat.c
	${CC} -c ${CFLAGS} $(SRC)/strncat.c
strncmp.o : $(SRC)/strncmp.c
	${CC} -c ${CFLAGS} $(SRC)/strncmp.c
strncpy.o : $(SRC)/strncpy.c
	${CC} -c ${CFLAGS} $(SRC)/strncpy.c
strnwrd.o : $(SRC)/strnwrd.c
	${CC} -c ${CFLAGS} $(SRC)/strnwrd.c
strpat.o : $(SRC)/strpat.c
	${CC} -c ${CFLAGS} $(SRC)/strpat.c
strpbrk.o : $(SRC)/strpbrk.c
	${CC} -c ${CFLAGS} $(SRC)/strpbrk.c
strposn.o : $(SRC)/strposn.c
	${CC} -c ${CFLAGS} $(SRC)/strposn.c
strrchr.o : $(SRC)/strrchr.c
	${CC} -c ${CFLAGS} $(SRC)/strrchr.c
strrpset.o : $(SRC)/strrpset.c
	${CC} -c ${CFLAGS} $(SRC)/strrpset.c
strrrot.o : $(SRC)/strrrot.c
	${CC} -c ${CFLAGS} $(SRC)/strrrot.c
strrset.o : $(SRC)/strrset.c
	${CC} -c ${CFLAGS} $(SRC)/strrset.c
strset.o : $(SRC)/strset.c
	${CC} -c ${CFLAGS} $(SRC)/strset.c
strsort.o : $(SRC)/strsort.c
	${CC} -c ${CFLAGS} $(SRC)/strsort.c
strspn.o : $(SRC)/strspn.c
	${CC} -c ${CFLAGS} $(SRC)/strspn.c
strstr.o : $(SRC)/strstr.c
	${CC} -c ${CFLAGS} $(SRC)/strstr.c
strtok.o : $(SRC)/strtok.c
	${CC} -c ${CFLAGS} $(SRC)/strtok.c
strtoupp.o : $(SRC)/strtoupp.c
	${CC} -c ${CFLAGS} $(SRC)/strtoupp.c
termio.o : $(SRC)/termio.c
	${CC} -c ${CFLAGS} $(SRC)/termio.c
terms.o : $(SRC)/terms.c
	${CC} -c ${CFLAGS} $(SRC)/terms.c
time.o : $(SRC)/time.c
	${CC} -c ${CFLAGS} $(SRC)/time.c
toupper.o : $(SRC)/toupper.c
	${CC} -c ${CFLAGS} $(SRC)/toupper.c
vsprintf.o : $(SRC)/vsprintf.c
	${CC} -c ${CFLAGS} $(SRC)/vsprintf.c
atod.o : $(SRC)/atod.c
	${CC} -c ${CFLAGS} $(SRC)/atod.c
read.o : $(SRC)/read.c
	${CC} -c ${CFLAGS} $(SRC)/read.c
bzero.o : $(SRC)/bzero.c
	${CC} -c ${CFLAGS} $(SRC)/bzero.c
calloc.o : $(SRC)/calloc.c
	${CC} -c ${CFLAGS} $(SRC)/calloc.c
atof.o : $(SRC)/atof.c
	${CC} -c ${CFLAGS} $(SRC)/atof.c
atol.o : $(SRC)/atol.c
	${CC} -c ${CFLAGS} $(SRC)/atol.c
rand.o : $(SRC)/rand.c
	${CC} -c ${CFLAGS} $(SRC)/rand.c
open.o : $(SRC)/open.c
	${CC} -c ${CFLAGS} $(SRC)/open.c
close.o : $(SRC)/close.c
	${CC} -c ${CFLAGS} $(SRC)/close.c
write.o : $(SRC)/write.c
	${CC} -c ${CFLAGS} $(SRC)/write.c
getmach.o : $(SRC)/getmach.c
	${CC} -c ${CFLAGS} $(SRC)/getmach.c
atoi.o : $(SRC)/atoi.c
	${CC} -c ${CFLAGS} $(SRC)/atoi.c
realloc.o : $(SRC)/realloc.c
	${CC} -c ${CFLAGS} $(SRC)/realloc.c
fileno.o : $(SRC)/fileno.c
	${CC} -c ${CFLAGS} $(SRC)/fileno.c
scanf.o : $(SRC)/scanf.c
	${CC} -c ${CFLAGS} $(SRC)/scanf.c
files.o : $(SRC)/files.c
	${CC} -c ${CFLAGS} $(SRC)/files.c
feof.o : $(SRC)/feof.c
	${CC} -c ${CFLAGS} $(SRC)/feof.c
signal.o : $(SRC)/signal.c
	${CC} -c ${CFLAGS} $(SRC)/signal.c
eraline.o : $(SRC)/eraline.c
	${CC} -c ${CFLAGS} $(SRC)/eraline.c
getchar.o : $(SRC)/getchar.c
	${CC} -c ${CFLAGS} $(SRC)/getchar.c
getc.o : $(SRC)/getc.c
	${CC} -c ${CFLAGS} $(SRC)/getc.c
ungetc.o : $(SRC)/ungetc.c
	${CC} -c ${CFLAGS} $(SRC)/ungetc.c
putchar.o : $(SRC)/putchar.c
	${CC} -c ${CFLAGS} $(SRC)/putchar.c
puts.o : $(SRC)/puts.c
	${CC} -c ${CFLAGS} $(SRC)/puts.c
putc.o : $(SRC)/putc.c
	${CC} -c ${CFLAGS} $(SRC)/putc.c
fgets.o : $(SRC)/fgets.c
	${CC} -c ${CFLAGS} $(SRC)/fgets.c
fputs.o : $(SRC)/fputs.c
	${CC} -c ${CFLAGS} $(SRC)/fputs.c
fflush.o : $(SRC)/fflush.c
	${CC} -c ${CFLAGS} $(SRC)/fflush.c
sprintf.o : $(SRC)/sprintf.c
	${CC} -c ${CFLAGS} $(SRC)/sprintf.c
fprintf.o : $(SRC)/fprintf.c
	${CC} -c ${CFLAGS} $(SRC)/fprintf.c
vfprintf.o : $(SRC)/vfprintf.c
	${CC} -c ${CFLAGS} $(SRC)/vfprintf.c
fwrite.o : $(SRC)/fwrite.c
	${CC} -c ${CFLAGS} $(SRC)/fwrite.c
fread.o : $(SRC)/fread.c
	${CC} -c ${CFLAGS} $(SRC)/fread.c
fseek.o : $(SRC)/fseek.c
	${CC} -c ${CFLAGS} $(SRC)/fseek.c
isalnum.o : $(SRC)/isalnum.c
	${CC} -c ${CFLAGS} $(SRC)/isalnum.c
isalpha.o : $(SRC)/isalpha.c
	${CC} -c ${CFLAGS} $(SRC)/isalpha.c
iscntrl.o : $(SRC)/iscntrl.c
	${CC} -c ${CFLAGS} $(SRC)/iscntrl.c
isdigit.o : $(SRC)/isdigit.c
	${CC} -c ${CFLAGS} $(SRC)/isdigit.c
islower.o : $(SRC)/islower.c
	${CC} -c ${CFLAGS} $(SRC)/islower.c
isprint.o : $(SRC)/isprint.c
	${CC} -c ${CFLAGS} $(SRC)/isprint.c
isspace.o : $(SRC)/isspace.c
	${CC} -c ${CFLAGS} $(SRC)/isspace.c
isxdigit.o : $(SRC)/isxdigit.c
	${CC} -c ${CFLAGS} $(SRC)/isxdigit.c
fclose.o : $(SRC)/fclose.c
	${CC} -c ${CFLAGS} $(SRC)/fclose.c
gets.o : $(SRC)/gets.c
	${CC} -c ${CFLAGS} $(SRC)/gets.c
fgetc.o : $(SRC)/fgetc.c
	${CC} -c ${CFLAGS} $(SRC)/fgetc.c
strcpy.o : $(SRC)/strcpy.c
	${CC} -c ${CFLAGS} $(SRC)/strcpy.c
qsort.o : $(SRC)/qsort.c
	${CC} -c ${CFLAGS} $(SRC)/qsort.c
getopt.o : $(SRC)/getopt.c
	${CC} -c ${CFLAGS} $(SRC)/getopt.c
