#!/bin/sh

if [ $# -ne 1 ]; then
	echo "usage: $0 TGZFILE"
	exit 1
fi

if [ -f $1 ]; then
	echo "$1: already exists"
	exit 1
fi

if [ ! -r exclude ]; then
	echo "$0: must be run in PMON root dir"
	exit 1
fi


gtar -cv -f- --portability --exclude-from=exclude . | gzip -9 >$1
