# $Id: rules.mk,v 1.2 1996/01/16 14:23:35 chris Exp $ 
##################################################
#          Do Not Edit This File                 #
#     Add any new modules to files.mk            #
##################################################
main.o : $(SRC)/main.c
	${CC} -c ${CFLAGS} $(SRC)/main.c
commands.o : $(SRC)/commands.c
	${CC} -c ${CFLAGS} $(SRC)/commands.c
dis.o : $(SRC)/dis.c
	${CC} -c ${CFLAGS} $(SRC)/dis.c
hist.o : $(SRC)/hist.c
	${CC} -c ${CFLAGS} $(SRC)/hist.c
machine.o : $(SRC)/machine.c
	${CC} -c ${CFLAGS} $(SRC)/machine.c
regs.o : $(SRC)/regs.c
	${CC} -c ${CFLAGS} $(SRC)/regs.c
sym.o : $(SRC)/sym.c
	${CC} -c ${CFLAGS} $(SRC)/sym.c
set.o : $(SRC)/set.c
	${CC} -c ${CFLAGS} $(SRC)/set.c
stty.o : $(SRC)/stty.c
	${CC} -c ${CFLAGS} $(SRC)/stty.c
more.o : $(SRC)/more.c
	${CC} -c ${CFLAGS} $(SRC)/more.c
load.o : $(SRC)/load.c
	${CC} -c ${CFLAGS} $(SRC)/load.c
go.o : $(SRC)/go.c
	${CC} -c ${CFLAGS} $(SRC)/go.c
debug.o : $(SRC)/debug.c
	${CC} -c ${CFLAGS} $(SRC)/debug.c
regdefs.o : $(SRC)/regdefs.c
	${CC} -c ${CFLAGS} $(SRC)/regdefs.c
memtst.o : $(SRC)/memtst.c
	${CC} -c ${CFLAGS} $(SRC)/memtst.c
cmdtable.o : $(SRC)/cmdtable.c
	${CC} -c ${CFLAGS} $(SRC)/cmdtable.c
sbrk.o : $(SRC)/sbrk.c
	${CC} -c ${CFLAGS} $(SRC)/sbrk.c
demo.o : $(SRC)/demo.c
	${CC} -c ${CFLAGS} $(SRC)/demo.c
mips.o : $(SRC)/mips.S
	${CC} -c ${ASFLAGS} $(SRC)/mips.S
