# $Id: rules.mk,v 1.2 1996/01/16 14:19:24 chris Exp $ 
##################################################
#          Do Not Edit This File                 #
#     Add any new modules to files.mk            #
##################################################
